# Generated by Django 3.0.4 on 2020-03-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thealth', '0003_feed_feedpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=11)),
                ('member_id', models.CharField(max_length=11)),
                ('comment', models.CharField(max_length=1000)),
                ('commented_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=11)),
                ('member_id', models.CharField(max_length=11)),
                ('liked_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=11)),
                ('member_id', models.CharField(max_length=11)),
                ('saved_time', models.CharField(max_length=50)),
            ],
        ),
    ]
