# Generated by Django 3.0.4 on 2020-03-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thealth', '0004_feedcomment_feedlike_feedsave'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=11)),
                ('follower_id', models.CharField(max_length=11)),
                ('date_time', models.CharField(max_length=50)),
            ],
        ),
    ]
